/*
 * Copyright 2020 Google LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

object Libs {
    const val ACTIVITY_KTX = "androidx.activity:activity-ktx"
    const val ANDROIDX_HILT_COMPILER = "androidx.hilt:hilt-compiler"
    const val APPCOMPAT = "androidx.appcompat:appcompat"
    const val ARCH_TESTING = "androidx.arch.core:core-testing"
    const val ARCORE = "com.google.ar:core"
    const val BENCHMARK = "androidx.benchmark:benchmark-junit4"
    const val BROWSER = "androidx.browser:browser"
    const val CARDVIEW = "androidx.cardview:cardview"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val CRASHLYTICS = "com.crashlytics.sdk.android:crashlytics"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
    const val COROUTINES_TEST = "org.jetbrains.kotlinx:kotlinx-coroutines-test"
    const val DRAWER_LAYOUT = "androidx.drawerlayout:drawerlayout"
    const val ESPRESSO_CONTRIB = "androidx.test.espresso:espresso-contrib"
    const val ESPRESSO_CORE = "androidx.test.espresso:espresso-core"
    const val EXT_JUNIT = "androidx.test.ext:junit"
    const val FIREBASE_ANALYTICS = "com.google.firebase:firebase-analytics-ktx"
    const val FIREBASE_CRASHLYTICS = "com.google.firebase:firebase-crashlytics-ktx"
    const val FIREBASE_IID = "com.google.firebase:firebase-iid"
    const val FIREBASE_AUTH = "com.google.firebase:firebase-auth-ktx"
    const val FIREBASE_CONFIG = "com.google.firebase:firebase-config-ktx"
    const val FIREBASE_FIRESTORE = "com.google.firebase:firebase-firestore-ktx"
    const val FIREBASE_FUNCTIONS = "com.google.firebase:firebase-functions-ktx"
    const val FIREBASE_MESSAGING = "com.google.firebase:firebase-messaging"
    const val FRAGMENT = "androidx.fragment:fragment"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx"
    const val GLIDE = "com.github.bumptech.glide:glide"
    const val GLIDE_COMPILER = "com.github.bumptech.glide:compiler"
    const val GOOGLE_MAP_UTILS = "com.google.maps.android:android-maps-utils"
    const val GOOGLE_PLAY_SERVICES_MAPS = "com.google.android.gms:play-services-maps"
    const val GOOGLE_PLAY_SERVICES_LOCATION = "com.google.android.gms:play-services-location"
    const val GOOGLE_PLAY_SERVICES_VISION = "com.google.android.gms:play-services-vision"
    const val HUAWEI_SERVICES_LOCATION = "com.huawei.hms:location"
    const val GSON = "com.google.code.gson:gson"
    const val HAMCREST = "org.hamcrest:hamcrest-library"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_VIEWMODEL = "androidx.hilt:hilt-lifecycle-viewmodel"
    const val HILT_COMPILER = "com.google.dagger:hilt-android-compiler"
    const val HILT_TESTING = "com.google.dagger:hilt-android-testing"
    const val INK_PAGE_INDICATOR = "com.pacioianu.david:ink-page-indicator"
    const val JUNIT = "junit:junit"
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib-jdk7"
    const val LIFECYCLE_COMPILER = "androidx.lifecycle:lifecycle-compiler"
    const val LIFECYCLE_LIVE_DATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx"
    const val LIFECYCLE_VIEW_MODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx"
    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx"
    const val OKHTTP = "com.squareup.okhttp3:okhttp"
    const val OKHTTP_LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor"
    const val OKIO = "com.squareup.okio:okio"
    const val ROOM_COMPILER = "androidx.room:room-compiler"
    const val ROOM_KTX = "androidx.room:room-ktx"
    const val ROOM_RUNTIME = "androidx.room:room-runtime"
    const val TIMBER = "com.jakewharton.timber:timber"
    const val VIEWPAGER2 = "androidx.viewpager2:viewpager2"
    const val ANKO_COMMONS = "org.jetbrains.anko:anko-commons"
    const val ANKO_SUPPORT_V4_COMMONS = "org.jetbrains.anko:anko-support-v4-commons"
    const val permissions_dispatcher_runtime = "com.github.permissions-dispatcher:permissionsdispatcher"
    const val permissions_dispatcher_processor = "com.github.permissions-dispatcher:permissionsdispatcher-processor"
    const val bga_refreshlayout = "cn.bingoogolapple:bga-refreshlayout"
    const val pageindicatorview = "com.romandanylyk:pageindicatorview"
    const val ANDROID_MATERIAL = "com.google.android.material:material"
    const val support_cardview = "androidx.cardview:cardview"
    const val retrofit2 = "com.squareup.retrofit2:retrofit"
    const val retrofit2_converter_scalars = "com.squareup.retrofit2:converter-scalars"
    const val retrofit2_adapter_rxjava = "com.squareup.retrofit2:adapter-rxjava"
    const val aliyun_oss = "com.aliyun.dpa:oss-android-sdk"
    const val ratingbar = "com.hedgehog.ratingbar:app"
    const val PickerView = "com.contrarywind:Android-PickerView"
    const val calendarview = "com.haibin:calendarview"
    const val CustomPopwindow = "com.github.pinguo-zhouwei:CustomPopwindow"
    const val hms_scan = "com.huawei.hms:scan"
    const val meglive_still = "com.meglive:still"

    // flash base libs
    const val ADDRESS_LIB = "com.flashexpress:address_lib"
    const val ADDRESS_LIB_OTHER = "com.flashexpress:address_lib_other"
    const val ADDRESS_PARSER = "com.flashexpress:addressparser"
    const val FLASH_CORE = "com.flashexpress:core"
    const val FLASH_CORE_NET = "com.flashexpress:core-net"
    const val FLASH_CORE_NET_OKHTTP = "com.flashexpress:core-net-okhttp"
    const val FLASH_CORE_NET_RETROFIT = "com.flashexpress:core-net-retrofit"
    const val FLASH_CORE_UI = "com.flashexpress:core-ui"
    const val FLASH_GOOGLE_AUTHENTICATOR = "com.flashexpress:google-authenticator"
    const val FLASH_IDENTITY_CAMERA = "com.flashexpress:identity-camera"
    const val FLASH_IDENTITY_CERTIFICATION = "com.flashexpress:identity-certification"
    const val FLASH_IDENTITY_CERTIFICATION_PH = "com.flashexpress:identity-certification-ph"
    const val FLASH_TOOLS_DOWNLOAD = "com.flashexpress:tools-download"
    const val FLASH_TOOLS_IMAGES = "com.flashexpress:tools-images"
    const val FLASH_WEB = "com.flashexpress:web"
    const val FLASH_WIDGET = "com.flashexpress:widget"
}
